### ISSUE TITLE
请教一下，使用方法看不大明白

### ISSUE THREAD

**Issue by tianziabcd** [H5Z2P5Z2P/autoremove-torrents#1]
请教一下，使用方法的流程可否具体一些，新手不懂代码，照着操作的话，需要写明白一些，最后加入定时任务，时间间隔怎么定义呢？

**Comment by huaihuai0406** [comment]
ssh 到群晖
选择一个路径存放 autoremove-torrents 数据 用来挂载进docker
执行下边的这些命令
mkdir data
cd data
mkdir logs
pwd
显示结果(/xxx/xxxx/data/logs)

pwd 会显示当前路径 把显示的结果(/xxx/xxxx/data/logs) 替换掉 docker执行命令的 /path/to/data 这一段
